### ISSUE TITLE
Review expandAdaptors

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#264]
Adaptors functions should try to "expand" all of their arguments, like this:

```
export function get(path, params, callback) {
  return state => {
    const resolvedPath = expandReferences(path)(state);
    const resolvedParams = http.expandRequestReferences(params)(state);

    // ....
```
This is really important for enabling operations to be nicely composed, like this:
```
each(
 'patients',
  upsert('trackedEntityInstance', state => ({
    name: state.data.name,
    age: state.data.age
  }));
});
```

It turns out that at least one vitally important function, `dhis2.upsert`, does NOT expand its references. So actually the code I've pasted above will not work.

We should fix this ASAP, and probably investigate other commonly used adaptors.

Here's a list of currently used adaptors (provided by Mtuchi):
```
[
    "asana-v1.0.1",
    "commcare-",
    "dhis2-",
    "godata-",
    "googlesheets-",
    "http-",
    "kobotoolbox-",
    "mailchimp-",
    "mailgun-",
    "mssql-",
    "openfn-",
    "openmrs-v1.0.1",
    "postgresql-",
    "primero-v2.10.0",
    "rapidpro-v0.4.7",
    "salesforce-",
    "sftp-",
    "surveycto-",
    "telerivet-"
]
```

**Comment by taylordowns2000** [comment]
hey @josephjclark , i had a good look around today and I _think_ we're actually ok for the most part. the dhis2 one is a weird one... in short, to me it looks like it _does_ expand references since it's composed of three helper functions which always expand refs...

so it takes the unresolved stuff and [passes it into get](https://github.com/OpenFn/adaptors/blob/main/packages/dhis2/src/Adaptor.js#L500C16-L504), which expands.

it then takes the unresolved data and passes it into [create](https://github.com/OpenFn/adaptors/blob/main/packages/dhis2/src/Adaptor.js#L512) or [update](https://github.com/OpenFn/adaptors/blob/main/packages/dhis2/src/Adaptor.js#L518).

shouldn't that actually do the expansion? cc @mtuchi , as I know he'll be interested in this!

**Comment by josephjclark** [comment]
Looks like you're right! Expansion takes place further down. Happy to close this issue.

Some musings which may trigger new issues:

There's an argument that every function should do expansion at the top as a standard practice. That's clear and declarative and robust if any underlying function changes (although I don't see why it would).

I'd also like to see a nice clean API like this at the top of every adaptor:
```
const [resolvedResourceType, resolvedData, resolvedOptions] = expandReferences(state, resourceType, data, options)
```

I don't love the `resolved` prefix though. maybe `$data` or `_data` would be better conventions?

I suppose you could do:

```
const resolved = expandReferences(state, { resourceType, data, options })
post(resolved.resourceType)
```

As a wider issue I'd like cleaner distinction in adaptors between operation factories (functions which return operations, used in job code) and utility functions (functions exported from common to be used by other adaptors, but are not themselves operations). Stuff like `expandReferences()` and `lastReference()` and even `http.post` don't really feel like they should be structured as operation factories,
