### ISSUE TITLE
Update Oauth2-based configuration schemas to use snake case

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/adaptors#294]
In OpenFn v1, we camelCased the oauth2 payload before storing it as a `credential.body`, and subsequently all the adaptors expect `configuration.accessToken` instead of `configuration.access_token`.

In OpenFn v2, we're not doing that camelCasing currently, and the [oauth2 spec seems to specify that snake_case is standard](https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/).

Should we deprecate `accessToken` and make `access_token` the new standard for these Oauth-based configuration schemas?

To aide the transition, we could provide a helper that prints a little deprecation warning and creates a new `access_token` key if it only finds `accessToken`

cc @stuartc , @josephjclark , @mtuchi - would love your thoughts on this.

**Comment by josephjclark** [comment]
This stuff is always difficult because the standard for oauth is in direct contrast to the standard for Javascript. It is always curious, uncomfortable and sometimes frustrating to switch to snake case.

On the other hand, if you're reading the oauth docs, or are used to oauth, it feels strange to use camelCase.

My instinct is that we should present a conventional Javascript style across all our adaptors. If you're using an adaptor, you should expect to define camelCased objects. End of story. 

But we don't need to be strict about it. We could choose to convert keys into snake case unless they're already snake case - in which case both styles will actually work. Lodash provides helper functions for this. In that model we'd officially be describing and documenting a camelCase format, but also be accepting snake_case.

**Comment by taylordowns2000** [comment]
Thanks for this. I'm caught in two minds here. Things I'm considering:

1. I really _don't_ want to have to enforce add a `camelizeKeys` step when we save Oauth credentials in Lightning (cc @stuartc ) 
2. I like the idea of our configuration schemas looking like normal Javascript.
3. When I see [this code](https://github.com/OpenFn/adaptors/blob/main/packages/googlesheets/src/Adaptor.js#L55-L58) I feel like we _should_ simply use underscores for the Oauth JSON credential body. In that snippet we are grabbing the `accessToken` from state.configuration and then converting it to `access_token` so we can use it in the official Google Oauth Javascript client.
4. If we anticipate people using this adaptor from the CLI also, would it be better to have it be perfectly compatible with the Oauth2 standard? In other words, in order to use the google sheets adaptor (or any adaptor that uses Oauth2 to log in) wouldn't it be nice to allow people to use a full JSON oauth2 credential?

@josephjclark , would you be down with me modifying the adaptors so that they expect snake_case (and modifying the credential schemas for oauth2... which need to be different* anyway) and can attempt to snake-case (verb, transitive) stuff that comes in in camelCase?

**Comment by josephjclark** [comment]
hmm that's a fair point - when we're talking about credentials then you're just authoring a JSON object. You're not in Javascriptland and snake case conventions are perfectly sensible (especially as oauth is natively snake case).

I was speaking more about adaptor APIs and job code than credential data.

Context is king.

Ok, sure, let's do as you suggest:

* Use snake_case in the schema
* Continue to support accessToken but log a deprecation warning
