### ISSUE TITLE
`commcare` add function

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptors#528]
## Request
Currently our adaptor does not support extracting `case`, `form`, `user`, `group` and `lookup table` data out of CommCare.

See CommCare API docs: 
1. [Get cases](https://dimagi.atlassian.net/wiki/spaces/commcarepublic/pages/2143957300/List+Cases+version+3)
2. [Get a single case](https://dimagi.atlassian.net/wiki/spaces/commcarepublic/pages/2143957360)
3. [Get users](https://dimagi.atlassian.net/wiki/spaces/commcarepublic/pages/2143957296/List+Mobile+Workers)
4. [Get lookup table data](https://dimagi.atlassian.net/wiki/spaces/commcarepublic/pages/2143957453/Fixture+Data+APIs+or+Lookup+Tables)
5. [Get forms](https://dimagi.atlassian.net/wiki/spaces/commcarepublic/pages/2143957334/List+Forms)
6. [Get a single form](https://dimagi.atlassian.net/wiki/spaces/commcarepublic/pages/2143957429/Form+Data+APIs)

_Plus_ we should also ensure that all `http` functions are available in this adaptor, in case users want to send http requests to other api endpoints not listed above. 

## Examples
- See get `cases` data example: https://github.com/OpenFn/lwala/blob/master/bulk/bulkGetCases-Person.js#L18-L19
- See get `form` data example: https://github.com/OpenFn/grassroot-soccer/blob/master/jobs/1.getForms.js

## To test
See LP `CommCare Demo Project` for a credential to our `test` project.

**Comment by josephjclark** [comment]
Note from mtuchi: we may want to rename "application name" to "domain" to better reflect commcare's own language.

Also app id may not be needed in each request

**Comment by josephjclark** [comment]
Hi @aleksa-krolls,

How important is this ticket? I am thinking about asking Hunter to do it now as she's already working on the commcare adaptor. Make sense to me to pack a few features in while shes in the headspace for it.

After a quick chat with @mtuchi , I would suggest we expose general `get` and `post` helper operations, so that users can get at any resources they need.

```
get('cases', { query: { name: 'Buck Rogers' }})
```
or
```
```
get('/cases?name="Buck Rogers")  // (note to me, we need to ensure the URL is safely escaped, does undici do that for us?)
```

Then later we can think about adding special `getCase`, `getCases` etc operations for the most commonly used ones.

Sound cool?

**Comment by aleksa-krolls** [comment]
@josephjclark I think extra time spent here to get it right is well spent. There are handful of customers integrating with Commcare, but using http ... so I want to get them using this adaptor. Plus we have a big CommCare integration project kicking off end of month that will need this too :)

**Comment by josephjclark** [comment]
Great - we'll invest a couple of days into this then and have a shiny new release for you next week. Thanks!

**Comment by josephjclark** [comment]
@christad92 just a heads up that we'd like Hunter to tackle this issue after she's done the current commcare one

**Comment by aleksa-krolls** [comment]
cool and fyi @AishaHassen will be able to provide QA and implementation feedback :)

**Comment by aleksa-krolls** [comment]
@hunterachieng I want to check on the estimate here. I'm seeing `96 hours` - is that right that this will take 12 days (12 days * 8 hrs = 96hrs) to implement these functions? That feels really high

cc @josephjclark @mtuchi

**Comment by josephjclark** [comment]
Hmm. I wouldn't want to give you a number in hours, but I don't think this is a very big job.

We need one generalised helper function for this, which should be super easy to add on top of the existing `request` we just added.

There are a couple of tidyups that Mutchi suggests, but they're only small.

There will be a review cycle but in terms of focused working hours that should be low. And again the scope for the work is limited so I don't expect this to be too high.

@hunterachieng I'm happy to talk through the exact scoping, but- my feeling is that this is gonna be less than ten hours.

**Comment by hunterachieng** [comment]
@aleksa-krolls  apologies,  I was estimating with 24 hours and not 8 hours. I included extra time for reviews as well but I agree with @josephjclark 's assessment. If its not large then I can change the estimate to 8 hours

**Comment by aleksa-krolls** [comment]
hey @hunterachieng is this what you're working on today? If yes, friendly reminder to move over to the `In Progress` column so we can monitor progress on getting through the backlog. Thanks :)

**Comment by hunterachieng** [comment]
@aleksa-krolls  I am finalising on a few improvements for commcare then I hit the ground running with this task

**Comment by josephjclark** [comment]
@aleksa-krolls That's my fault - I've got Hunter doing a couple of extra bits on the other PR before she moves on. Want to make sure we're building on stable ground here!

**Comment by hunterachieng** [comment]
@aleksa-krolls  Sounds good

**Comment by josephjclark** [comment]
I've just spun #562 out of this thread to capture the config schema changes. It's only a small change and we have to do it alongside the upcoming release.

**Comment by josephjclark** [comment]
@hunterachieng Just one test on `get` please! getCases will be fine -  it just proves out the generic get handler

**Comment by hunterachieng** [comment]
@josephjclark  Yes I am writing one test. I was just testing the scenarios manually first

**Comment by josephjclark** [comment]
Hey @aleksa-krolls , the generic `get()` helper is in.

Do we want a `post` helper too? Or is that  for another day?

**Comment by aleksa-krolls** [comment]
@josephjclark yes, please! But let's close out this issue. For the post, I created this issue #570 - great if you and hunter can put an estimate there to help us understand what's left and what Hunter can take on next week.

**Comment by AishaHassen** [comment]
@hunterachieng QA testing comments: 
1. Documentations: add more examples on the get function. The current example only shows fetching a list of cases, add an example that shows fetching a single value(you can make this second example on user). 
2. Documentations: List out the possible params either in the docs, e.g(Limit, offset...)
3. Error Handling: I tried to do `get("users")` instead of `get("user")` and got the error message below in the log. A better response would be something that indicates that the requested resource does not exist on Commcare
![image](https://github.com/OpenFn/adaptors/assets/167166847/0c36064c-991e-4564-86d3-bf44689d6f22)
4. Error handling: When getting a user by Id that doesn't exist, I am getting a `Job Error`. A better response would be that that resource with the specified id does not exisit
5. running the fetchReportData manages to post data to the desination but fails with this error afterwards:
<img width="1507" alt="Screenshot 2024-05-30 at 15 27 26" src="https://github.com/OpenFn/adaptors/assets/167166847/08d41f93-8323-45ed-85b9-aed99b0f6a2c">
6. I don't see post function on the docs on the job editor modal on app.openfn.org but i see it on doc.openfn.org
7. Examples on docs: Nawiri and Registration forms seem to be empty
