### ISSUE TITLE
Passing variable to getValues throws error

### ISSUE THREAD

**Issue by dcjohnson24** [OpenFn/adaptors#719]
## Describe the bug and expected behavior 
`getValues` from the Googlesheets adaptor does not accept variables for arguments, but `batchUpdateValues` can.

```javascript
fn(state => {
  
    const spreadsheetId = '1jj2dIhRv5Fk323YinIxAvp7rizoKLHl33bu9gaH1euU'
    return {...state, spreadsheetId}
})
getValues(
    state.spreadsheetId,
    'Sheet1!B:D',
)
```
will throw the error `AdaptorError: Missing required parameters: spreadsheetId`

but `getValues('1jj2dIhRv5Fk323YinIxAvp7rizoKLHl33bu9gaH1euU', 'Sheet1!B:D')` passes.

`getValues` should be able to read from state.

**Comment by josephjclark** [comment]
Hey @dcjohnson24, thank you for raising this!

I think the problem is that you're passing `undefined` into `getValues` as the spreadsheet id. As a quick fix, can you test if this works?
```
getValues(
    '1jj2dIhRv5Fk323YinIxAvp7rizoKLHl33bu9gaH1euU',
    'Sheet1!B:D',
)
```

I'll write up an explanation now  :)

**Comment by josephjclark** [comment]
So what's going on here is a little bit complicated. There's a long explanation here in the [Job Writing Guide](https://docs.openfn.org/documentation/jobs/job-writing-guide#reading-state-lazily)

The short technical explanation is that Javascript will evaluate `state.spreadsheetId` before OpenFn executes your first `fn` block, so it hasn't actually been assigned a value yet.

Luckily the solution is simple: when referencing state in operations, use `$.` instead of `state.`. Like this:
```
fn(state => {
    const spreadsheetId = '1jj2dIhRv5Fk323YinIxAvp7rizoKLHl33bu9gaH1euU'
    return {...state, spreadsheetId}
})
getValues(
    $.spreadsheetId,
    'Sheet1!B:D',
)
```

`$.` is what we call the [Lazy State Operator](https://docs.openfn.org/documentation/jobs/job-writing-guide#the-lazy-state-operator). It tells the OpenFn compiler to replace `$.` with `(state) => state.`. This passes a _function_  as the value of `spreadSheetId`, and the `getValues` function will evaluate that function just before it runs at runtime, ensuring that it has the very latest value

Simple :sweat_smile: 

Just use `$.` instead of `state.` and everything should work.

You can of course just pass a function directly, like `getValues(state => state.spreadsheetId)`. But the `$` is cleaner and a good habit to pick up.

Note that you cant use `$` _inside_ a callback (but you don't need it there anyway, you should have a state object in scope)

**Comment by dcjohnson24** [comment]
Thanks for the detailed explanation. `$.spreadsheetId` works as expected. But why does `state.spreadsheetId` work in this case

```javascript
batchUpdateValues({
    spreadsheetId: state.spreadsheetId,

    range: 'Sheet1!A2:F',
    values: state => state.records
})
```
? Is it because `state.spreadsheetId` is evaluated inside the object first and then passed to `batchUpdateValues`?

**Comment by josephjclark** [comment]
That's probably working because it's relying on the initial state value.

Anything that relies on a mutation of state, any downstream operations, will evaluate too early (they'll actually also use the initial value)

Asynchronous JavaScript is a big part of the problem. Synchronous operations should also work without any fancy state stuff. But because most of our operations are async, we suggest using $ for all state references (incidentally, $ is quite a new solution to this old problem, you'll see other approaches across the docs)

I'm going to close out the issue but I'm happy to carry on the conversation :)

**Comment by dcjohnson24** [comment]
Okay, thanks for the explanation. I will switch to using $ notation.
