### ISSUE TITLE
`fhir` Support posting transaction bundle in the adaptor

### ISSUE THREAD

**Issue by muhammad-levi** [OpenFn/adaptors#90]
The documentation about batch/transaction from HL7 can be seen here: https://www.hl7.org/fhir/http.html#transaction

For example, I have created some scripts to post transaction bundle:
1. https://github.com/sid-indonesia/OpenFn-antenatal-care/blob/main/expressions/kobo-to-fhir-obsolete-pattern.js
2. https://github.com/sid-indonesia/OpenFn-antenatal-care/blob/main/expressions/kobo-to-fhir/basic-screening.js

The second one is much preferred as it shows the data pipeline neatly.

**Comment by mtuchi** [comment]
@muhammad-levi closing this since the helper function is already implemented, you can see the implimentation 
👉🏽  https://github.com/OpenFn/adaptors/blob/main/packages/fhir/src/Adaptor.js#L87 ,
Here is how to use the helper function 
```
createTransactionBundle({
  entry: [transactionBundle],
});
```
Let us know if we need to improve the `state.configuration` as for this implimentation it requires `{ resource, authType, token }`
